spring:
  datasource:
    username: root
    password: 1720Maximnn
    url: jdbc:mysql://localhost:3306/promenad?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

    properties:
      hibernate:
      format_sql: true
      show_sql: true

  profiles:
    active: prod   #2 types of profile: 'dev' - DEBUG level, 'prod' - INFO level
jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver


text.path: src\\main\\resources\\voice\\







