spring:
  datasource:
    username: postgres
    password: 9999
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none


    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: prod   #2 types of profile: 'dev' - DEBUG level, 'prod' - INFO level
jdbc:
  driverClassName: org.postgresql.Driver


text.path: src\\main\\resources\\voice\\
server:
  port: 8010






